[phases.setup]
nixPkgs = ["python312", "nodejs_20", "gcc"]

[phases.install]
cmds = [
  "python -m venv --copies /opt/venv",
  ". /opt/venv/bin/activate && pip install --upgrade pip && pip install -r requirements.txt",
  "npm install",
]

[phases.build]
cmds = [
  "npm run build",
  ". /opt/venv/bin/activate && python manage.py collectstatic --noinput -i src",
]

[start]
cmd = ". /opt/venv/bin/activate && gunicorn researchdoc.wsgi --log-file - --workers 2 --timeout 60"
